### ISSUE TITLE
I am learner.

### ISSUE THREAD

**Issue by Web95Dev** [SamSamskies/advancednostrsearch#12]
Why is npub field is required?
How can I get npub?

**Comment by SamSamskies** [comment]
A small minority of users on nostr post really nasty content. Requiring an npub helps make sure that the content from those users don't show up in the search results. You can enter anyone's npub. It doesn't have to be your own. For example, here's a link with my npub https://advancednostrsearch.vercel.app/?npub=npub1vp8fdcyejd4pqjyrjk9sgz68vuhq7pyvnzk8j0ehlljvwgp8n6eqsrnpsw&query=test

Here's some of the nostr clients that I enjoy using:
Snort - https://snort.social/
Coracle - https://coracle.social/notes
Damus - https://damus.io/

An npub will be generated for you when going through the sign up process for any of those apps.

**Comment by Web95Dev** [comment]
Thank you very much for the clear explanation. 

I am analyzing your code and learning a lot from it. I do have a question though. You mentioned that npub helps ensure that content from certain users does not appear in search results, but it seems like the search only filters by author (npub).

On another note, just to confirm, the Vercel app searches both by author (npub) and query. 
Is there any way to search exclusively by query, like Coracle? 
I believe that would be more beneficial than solely relying on author as a filter.

Once again, thank you for your help.

Regards,

Wilson

**Comment by SamSamskies** [comment]
Without some kind of restrictions in place it's too easy too expose the really nasty content to people when they execute a search. I'm pretty sure most people really don't want to see this content. If they really want to see it, they can choose to enter an npub of someone that posts the borderline illegal content that that person posts.

You can click the checkbox under the npub field to include results from everyone that the owner of the npub follows. https://advancednostrsearch.vercel.app/?npub=npub1vp8fdcyejd4pqjyrjk9sgz68vuhq7pyvnzk8j0ehlljvwgp8n6eqsrnpsw&includeFollowed=1&query=gif&fromDate=2023-06-21

Feel free to fork the site and remove the restriction if you want a global search. I believe all you need to do is remove [these LOC](https://github.com/SamSamskies/advancednostrsearch/blob/main/src/App.tsx#L55-L61). Either that or just use Coracle. Coracle's search is more advanced. Just remember that I warned you about doing global searches. 😂

**Comment by Web95Dev** [comment]
Thank you!

But I know nostr is censorship-resistant social network.

**Comment by Web95Dev** [comment]
Did you check try catch statement on line 65-74?
If npub is empty, catch statement get active.
