### ISSUE TITLE
Basic search not working

### ISSUE THREAD

**Issue by dtdannen** [SamSamskies/advancednostrsearch#23]
Tried both in the deployed app at https://advancednostrsearch.vercel.app/ and running locally, for example using dergigi's npub and searching for "GM" doesn't return anything, but there are lots of notes:

npub1dergggklka99wwrs92yz8wdjs952h2ux2ha2ed598ngwu9w7a6fsh9xzpc

"GM"

<img width="726" alt="image" src="https://github.com/user-attachments/assets/30ef7a40-5024-4bfb-8073-2d9eb27e972e">

**Comment by SamSamskies** [comment]
Try again. When nostr.band relay is down, it doesn't return any events. Search currently depends on that relay. I just tested and it's working now.
